# Tomcat
server:
  port: 10001

# Spring
spring:
  main:
    banner-mode: "console"
  application:
    # 应用名称
    name: content-service
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml

myminio:
  endpoint: http://localhost:9000
  accessKey: ruoyi
  secretKey: ruoyi123

vod:
 secretId: AKID66ye8PTLzQddQvJUTHsHTTHuRmupX1JN
 secretKey: tYPCv0veCXfaHrEOK3Ys1xgCVbT9cryt
 subAppId: 1500044320
 region: ap-chengdu
---
spring:
  ai:
    deepseek:
      api-key: sk-205fb87ba80946c08469c5d953c68481
      base-url: https://api.deepseek.com
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
        options:
          temperature: 0.7
